server:
  port: 2164
  forward-headers-strategy: framework
  servlet:
    context-path: /
  undertow:
    accesslog:
      prefix: "[DEMO-CONTA]"
  error:
    include-message: always

    spring:


spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/financeiro
    username: postgres
    password: Postgres2022!

  security:
    user:
        name: zedascouve
        password: 123@

  jpa:
    show-sql: true
    hibernate:
      ddl-auto=create-drop: drop-and-create

      