services:
  postgres:
    image: postgres
    volumes:
      - ./01-financeiro.sql:/docker-entrypoint-initdb.d/01-financeiro.sql
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"